### ISSUE TITLE
Any reason to use gulp/browserify over webpack?

### ISSUE THREAD

**Issue by anoadragon453** [filips123/ZeroTemplate#4]
I have no preference for either, just wondering what made you chose one over the other.

**Comment by filips123** [comment]
I created this template based on some other projects which also used Gulp and Browserify. I also don't have any preference for this, so I used Browserify.

Gulp is also used for site deployment so even if I would use Webpack, I would still have to use Gulp.

If there is any reason to use Webpack or another bundler, I can update code. I will maybe also look to some other bundlers like [Parcel](https://parceljs.org/), [Rollup](https://rollupjs.org/) or [Pika Pack](https://github.com/pikapkg/pack). But until then, Gulp and Browserify are probably OK.

**Comment by anoadragon453** [comment]
Sounds good. Thank you for making this!
